# Generated by Django 4.2.4 on 2023-08-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('email', models.CharField(max_length=180)),
            ],
            options={
                'db_table': 'usr_usuarios',
            },
        ),
    ]
