# Generated by Django 4.2.4 on 2023-11-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'rgt_item',
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=180, null=True, blank=True),
        ),
    ]
