# Generated by Django 4.2.4 on 2023-11-22 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webproject_back', '0002_estoqueitem_usuarios_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('item_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webproject_back.estoqueitem', verbose_name='Item do usuario no estoque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webproject_back.usuarios', verbose_name='ID do usuario')),
            ],
            options={
                'db_table': 'rgt_item_usuario',
            },
        ),
    ]
