# Generated by Django 4.2.4 on 2024-03-19 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webproject_back', '0003_itensusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensusuario',
            name='data_entrega',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
